name: TooManyBuckets
author: narrowtux
main: com.narrowtux.toomanybuckets.TMBMain
version: 0.1.2
depend: [NarrowtuxLib, Spout]
commands:
    toomanybuckets:
        aliases:
            - 'tmb'
            - 'tmi'
            - 'toomanyitems'
        usage: /<cmd>
        permission: 'toomanybuckets.use'
permissions:
    toomanybuckets.use:
        default: op